Docker container IDs dir now debug-friendly
A chattier, more friendly dockerize boot

diff --git a/libexec/dockerize b/libexec/dockerize
--- a/libexec/dockerize
+++ b/libexec/dockerize
@@ -3,8 +3,10 @@ set -e
 
 export __exec="eval"
 
+# Turn on debug mode, all commands are just dry runs, no action will be taken
 case "$1" in
 "-d" | "--debug" )
+  echo "Running in debug mode, no commands will be executed"
   set -x
   export __exec="echo"
   shift
@@ -12,12 +14,16 @@ esac
 
 if [ -z "$(type -p docker)" ]
 then
-  echo "dockerize: cannot find docker binary, did you install it?"
+  echo "Cannot find docker. Is docker installed and available in the PATH?"
   exit 1
 fi
 
 DOCKER_CIDS_DIR="/var/run/docker_cids"
-[ ! -d $DOCKER_CIDS_DIR ] && sudo mkdir $DOCKER_CIDS_DIR
+if [ ! -d $DOCKER_CIDS_DIR ]
+then
+  echo "Docker directory for storing container IDs does not exist, creating it now..."
+  $__exec "sudo mkdir $DOCKER_CIDS_DIR"
+fi
 
 resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
@@ -52,10 +58,9 @@ case "$command" in
 * )
   command_path="$(command -v "dockerize-$command" || true)"
   if [ ! -x "$command_path" ]; then
-    echo "dockerize: no such command \`$command'" >&2
+    echo "Dockerize does not have the \`$command' command" >&2
     exit 1
   fi
-
   shift
   exec "$command_path" "$@"
   ;;
